name = "telegram-chatbot"
main = "src/index.ts"
compatibility_date = "2024-11-06"

# [[d1_databases]]
# binding = "D1_BINDING"
# database_name = "your_db_name"
# database_id = "your_db_id"
# migrations_dir = "./migrations"